//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/RayCastInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @RayCastInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @RayCastInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""RayCastInput"",
    ""maps"": [
        {
            ""name"": ""Left-Click"",
            ""id"": ""e5b1c1d7-45e3-4f6c-9194-c5923bb8534f"",
            ""actions"": [
                {
                    ""name"": ""Shooting"",
                    ""type"": ""Button"",
                    ""id"": ""bd93cdb0-96d0-4669-b9ee-519354e82275"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7dbb6c30-e584-4e3a-a63b-111081413667"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shooting"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Left-Click
        m_LeftClick = asset.FindActionMap("Left-Click", throwIfNotFound: true);
        m_LeftClick_Shooting = m_LeftClick.FindAction("Shooting", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Left-Click
    private readonly InputActionMap m_LeftClick;
    private List<ILeftClickActions> m_LeftClickActionsCallbackInterfaces = new List<ILeftClickActions>();
    private readonly InputAction m_LeftClick_Shooting;
    public struct LeftClickActions
    {
        private @RayCastInput m_Wrapper;
        public LeftClickActions(@RayCastInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Shooting => m_Wrapper.m_LeftClick_Shooting;
        public InputActionMap Get() { return m_Wrapper.m_LeftClick; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(LeftClickActions set) { return set.Get(); }
        public void AddCallbacks(ILeftClickActions instance)
        {
            if (instance == null || m_Wrapper.m_LeftClickActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_LeftClickActionsCallbackInterfaces.Add(instance);
            @Shooting.started += instance.OnShooting;
            @Shooting.performed += instance.OnShooting;
            @Shooting.canceled += instance.OnShooting;
        }

        private void UnregisterCallbacks(ILeftClickActions instance)
        {
            @Shooting.started -= instance.OnShooting;
            @Shooting.performed -= instance.OnShooting;
            @Shooting.canceled -= instance.OnShooting;
        }

        public void RemoveCallbacks(ILeftClickActions instance)
        {
            if (m_Wrapper.m_LeftClickActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ILeftClickActions instance)
        {
            foreach (var item in m_Wrapper.m_LeftClickActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_LeftClickActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public LeftClickActions @LeftClick => new LeftClickActions(this);
    public interface ILeftClickActions
    {
        void OnShooting(InputAction.CallbackContext context);
    }
}
